SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES = fork0 \
	      fork1 \
	      forkfork \
	      forkwait \
	      exemple_system_0 \
	      mysystem \
	      waitstatus \
	      execdemo \
	      mini_bash 

all : ${EXECUTABLES}

clean :
	@rm -f core *.o *.out
	@rm -f ${EXECUTABLES}
