SHELL=/bin/sh

CFLAGS = -Wall -g -pedantic -std=c99

EXECUTABLES = capture \
		demo_alarm \
		demo_alarm_console \
		demo_kill_sleep \
		demo_kill_suicide \
		exemple_nice \
		s179

all : ${EXECUTABLES}

clean :
	@rm -f core *.o *.out
