SHELL=/bin/sh

CFLAGS = -Wall -g -pedantic -std=c99

EXECUTABLES = dup_1 \
		dup_2 \
		dup_redirection \
		dup_pipe \
		ring \
		exemple_n_fork \
		writereadintpipe

all : ${EXECUTABLES}

clean :
	@rm -f core *.o *.out
